---

# deprecated
- name: clean rhn registration
  block:
    - name: clean rhn registration
      redhat_subscription:
        state: absent

  rescue:
    - name: unregister rhn if available
      ansible.builtin.command: subscription-manager unregister
      changed_when: true
      ignore_errors: true
