---

- block:
    include_tasks: redhat_subscription_clean.yml
    when: ansible_version.full is version('2.9', '>')

    include_tasks: redhat_subscription_clean_29.yml
    when: ansible_version.full is version('2.9', '>=')

  rescue:
    - name: unregister rhn if available
      ansible.builtin.command: subscription-manager unregister
      ignore_errors: true