---
- include: rhn.yml
  when: ansible_distribution == 'RedHat'

- name: install ntp
  yum:
    name: ntp
    state: latest
  when: ansible_distribution == 'RedHat'

- name: start ntpd service
  service:
    name: ntpd
    enabled: yes
    state: started
  when: ansible_distribution == 'RedHat'

- name: enable ntp
  command: timedatectl set-ntp true
  when: ansible_distribution == 'RedHat'