---

- name: register
  ansible.builtin.import_tasks: register.yml
  when:
    - role_action == 'register'
    - ansible_distribution is defined
    - ansible_distribution == 'RedHat'

- name: unregister
  ansible.builtin.import_tasks: unregister.yml
  when:
    - role_action == 'unregister'
    - ansible_distribution is defined
    - ansible_distribution == 'RedHat'
