---

- include_tasks: register.yml
  when:
    - role_action == 'register'
    - ansible_distribution == 'RedHat'

- include_tasks: unregister.yml
  when:
    - role_action == 'unregister'
    - ansible_distribution == 'RedHat'