---

- name: include rhn subscription tasks
  include_tasks: rhn.yml
  when: ansible_distribution == 'RedHat'

- name: include ntp tasks
  include_tasks: ntp.yml
  when: ansible_distribution == 'RedHat'