---

- name: install ntp
  ansible.builtin.yum:
    name: ntp
    state: present

- name: start ntpd service
  ansible.builtin.service:
    name: ntpd
    enabled: yes
    state: started

- name: enable ntp
  ansible.builtin.command: timedatectl set-ntp true
  changed_when: False
  check_mode: no