---
- name: register with rhn
  community.general.redhat_subscription:
    state: present
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    auto_attach: "{{ rhn_auto_attach }}"
    pool: "{{ rhn_pool }}"
    force_register: "{{ rhn_force_register }}"
  register: register_rhn
  until: register_rhn is success
  delay: 3
  retries: 5
  when:
    - rhn_username is defined
    - rhn_password is defined
    - rhn_subscription is defined or (rhn_subscription is undefined and rhn_auto_attach|bool)