---

- name: include rhn subscription tasks
  block:
    - name: rhn
      ansible.builtin.include_tasks: rhn.yml
      when: ansible_version.full is version('2.10', '>=')

    - name: rhn (2.9)
      ansible.builtin.include_tasks: rhn_29.yml
      when: ansible_version.full is version('2.10', '<')
  when: not rhn_offline | bool

- name: include offline repos
  ansible.builtin.include_tasks: rhn_offline.yml
  when:
    - rhn_offline | bool
    - rhn_repo_base_url is defined

- name: include ntp tasks
  ansible.builtin.include_tasks: ntp.yml
  when: ansible_distribution_major_version|int < 8
