---

- name: enable built-in redhat repos
  ansible.builtin.command: subscription-manager config --rhsm.manage_repos=1
  changed_when: True
  ignore_errors: yes

- block:
    include_tasks: redhat_subscription_register.yml
    when: ansible_version.full is version('2.9', '>')

    include_tasks: redhat_subscription_register_29.yml
    when: ansible_version.full is version('2.9', '>=')

  rescue:
    - name: clean rhn registration if available
      ansible.builtin.command: subscription-manager clean
      ignore_errors: true

    - name: register with rhn
      ansible.builtin.command: subscription-manager register --username {{ rhn_username }} --password {{ rhn_password }}
      ignore_errors: true
      no_log: True
      when:
        - rhn_username is defined
        - rhn_password is defined

    - name: auto attach subscription
      ansible.builtin.command: subscription-manager attach --auto
      ignore_errors: true
      when: rhn_auto_attach|bool

    - block:
        - name: get pool id
          ansible.builtin.shell: >
            subscription-manager list
            --all --available --matches "{{ rhn_subscription }}"
            --pool-only | {{ rhn_pool_order }}
          register: pool_id
          until: pool_id is success
          retries: 5
          delay: 10
          ignore_errors: yes

        - debug:
            msg: "{{ pool_id.stdout }}"

        - name: add pool
          ansible.builtin.command: subscription-manager attach --pool={{ pool_id.stdout }}
          register: add_pool
          until: add_pool is success
          retries: 5
          delay: 10
          ignore_errors: yes
          when:
            - pool_id is succeeded
            - pool_id.stdout | length > 0
      when:
        - not rhn_auto_attach|bool
        - rhn_subscription is defined

- block:
    - name: enable repositories
      community.general.rhsm_repository:
        name: "{{ repo_channels }}"
        purge: yes

  rescue:
    - name: enable repositories
      ansible.builtin.command: subscription-manager repos --disable "*" --enable={{ repo_channels|join(' --enable=') }}
      when: rhn_subscription is defined
      register: task_result
      until: task_result is succeeded
      retries: 10
      delay: 5

- name: ensure yum-utils package present
  ansible.builtin.yum:
    name: yum-utils
    state: present