---

- name: disable built-in redhat repos
  command: subscription-manager config --rhsm.manage_repos=0
  changed_when: True
  ignore_errors: yes

- name: add offline repos
  yum_repository:
    name: "{{ item }}"
    description: "{{ item }}"
    file: offline_repos
    baseurl: "{{ rhn_repo_base_url }}/{{ item }}"
    gpgcheck: no
  loop: "{{ repo_channels }}"