---

- name: disable built-in redhat repos
  ansible.builtin.command: subscription-manager config --rhsm.manage_repos=0
  changed_when: true
  ignore_errors: true

- name: add offline repos
  ansible.builtin.yum_repository:
    name: "{{ item }}"
    description: "{{ item }}"
    file: offline_repos
    baseurl: "{{ rhn_repo_base_url }}/{{ item }}"
    gpgcheck: false
  loop: "{{ repo_channels }}"
