---

- name: include rhn subscription tasks
  block:
    - name: clean rhn
      ansible.builtin.include_tasks: clean_rhn.yml
      when: ansible_version.full is version('2.10', '>=')

    - name: clean rhn (2.9)
      ansible.builtin.include_tasks: clean_rhn_29.yml
      when: ansible_version.full is version('2.10', '<')
  when: not rhn_offline | bool

- name: include offline repo removal
  ansible.builtin.include_tasks: rhn_offline_clean.yml
  when:
    - rhn_offline | bool
    - rhn_repo_base_url is defined
